name: Build

on:
  workflow_call:
jobs:
  build:
    name: build workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      - name: Cache Node modules and jest.config.ts
        uses: actions/cache@v4
        with:
          key: ${{ github.sha }}-node-nextjs-cache
          path: |
            ~/.npm
            node_modules

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Check if .next folder exists
        run: |
          if [ -d ".next" ]; then
            echo ".next folder exists."
          else
            echo ".next folder does not exist!"
            exit 1
          fi

        # Optionally, store build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
