name: Build

on:
  workflow_call:
jobs:
  build:
    name: build workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      - name: Cache the dependencies
        uses: actions/cache@v4
        with:
          # Generate a new cache whenever packages or source files change.
          key: ${{ github.sha }}-node-nextjs-cache
          path: |
            node_modules
            .next/cache
            jest.config.js

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Check if .next folder exists
        run: |
          if [ -d ".next" ]; then
            echo ".next folder exists."
          else
            echo ".next folder does not exist!"
            exit 1
          fi

        # Optionally, store build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next/** # Use wildcard to ensure all files are included
          if-no-files-found: warn
          compression-level: 6
          include-hidden-files: true # Ensure hidden files are included
