name: Build

on:
  workflow_call:
jobs:
  build:
    name: build workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      - name: Cache the dependencies
        uses: actions/cache@v4
        with:
          # Generate a new cache whenever packages or source files change.
          key: ${{ github.sha }}-node-nextjs-cache
          path: |
            node_modules
            jest.config.js

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Check if .next folder exists
        run: |
          if [ -d ".next" ]; then
            echo ".next folder exists."
          else
            echo ".next folder does not exist!"
            exit 1
          fi
      - name: Cache the build artifacts for release
        uses: actions/cache@v4
        with:
          key: ${{ github.sha }}-next-build
          path: |
            .next/**
