name: Build

on:
  workflow_call:
jobs:
  build:
    name: build workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          key: ${{ github.sha }}-node-nextjs-cache
          path: ~/.npm

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Cache Build Artifacts
        uses: actions/cache@v4
        with:
          key: ${{ github.sha }}-node-nextjs-cache
          path: .next

      - name: Save Build Artifacts
        run: |
          mkdir -p build_artifacts
          cp -r .next build_artifacts
