name: Build wdorkflow

#trigger
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase
      - name: Checkout
        uses: actions/checkout@v4

      #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      #application level dependencies
      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Cache the dependencies
        uses: actions/cache@v4
        with:
          # Generate a new cache whenever packages or source files change.
          key: ${{ github.sha }}-node-nextjs-cache
          path: |
            node_modules
            .next

      # Upload the .next directory as an artifact cause caching is working in signal workflow for used in other workflow need to upload the artifacts
      - name: Upload .next artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build-${{ github.ref_name }}-${{ steps.timestamp.outputs.current }}
          path: ./.next
