name: CI workflow for next

#trigger
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

jobs:
  build:
    name: "Build the Next.js static Application"
    uses: ./.github/workflows/build.yaml

  test:
    needs: [build]
    name: test the application
    uses: ./.github/workflows/test.yaml

  code_scanning:
    name: "reusable for the code scanning"
    uses: ./.github/workflows/CodeScan.yaml
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

  artifact_upload:
    name: Artifacts folder upload to S3
    uses: ./.github/workflows/release.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRECT_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
      S3_BUCKET_NAME: ${{secrets.AWS_SECRECT_KEY}}
