name: CI workflow for next

#trigger
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase
      - name: Checkout
        uses: actions/checkout@v4

      #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      #application level dependencies
      - name: Install dependencies
        run: npm install

      - name: Cache the dependencies
        uses: actions/cache@v4
        with:
          # Generate a new cache whenever packages or source files change.
          key: ${{ github.sha }}-node-nextjs-cache
          path: |
            ~/.npm
              ${{ github.workspace }}/.next/cache

      - name: Build Next.js app
        run:
          npm run build
          # Step 6: Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out
