name: CI workflow for next

#trigger
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"
      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
