name: CI workflow for next

#trigger
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

jobs:
  build:
    name: "Build the Next.js static Application"
    uses: ./.github/workflows/build.yaml
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

  test:
    needs: [build]
    name: test the application
    uses: ./.github/workflows/test.yaml
