name: Upload the build artifact file

on:
  #trigger
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRECT_KEY:
        required: true
      S3_BUCKET_NAME:
        required: true

jobs:
  artifact_upload:
    name: Artifacts folder upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4

      - name: Download .next artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build-${{ github.ref_name }}-${{ steps.timestamp.outputs.current }}
          path: ./.next

      - name: aws credential configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRECT_KEY}}
      - name: check the AWS CLI
        run: |
          aws --version
      - name: uplad folder to the bucket S3
        run: |
          aws s3 cp ./.next s3://${{secrets.S3_BUCKET_NAME}} --recursive
