name: Test

on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Node Modules Cache
        id: node-cache
        uses: actions/cache@v2
        with:
          key: ${{ github.sha }}-node-nextjs-cache
          path: ~/.npm

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true' # Only run if cache is not hit
        run: npm install

      - name: Restore Build Artifacts
        run: |
          mkdir -p .next
          cp -r build_artifacts/.next .next

      - name: Run Tests
        run: npm test
