name: Test

on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Restore Node Modules Cache
        id: node-cache
        uses: actions/cache@v4
        with:
          key: ${{ github.sha }}-node-nextjs-cache
          path: ~/.npm

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true' # Only run if cache is not hit
        run: npm install

      - name: Restore Build Artifacts
        run: |
          if [ -d build_artifacts/.next ]; then
            mkdir -p .next
            cp -r build_artifacts/.next .next
          else
            echo "Build artifacts not found. Skipping restore."
          fi

      - name: Run Tests
        run: npm test
