name: Test workflow

on:
  workflow_call:
jobs:
  test:
    name: test the application
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase
      - name: Checkout
        uses: actions/checkout@v4

      #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"
      #Restore the cache
      - name: restore the cahe
        id: cache-restore
        uses: actions/cache@v4
        with:
          # Generate a new cache whenever packages or source files change.
          path: |
            node_modules
            .next/cache
             jest.config.js
          key: ${{ github.sha }}-node-nextjs-cache

          # In cahce miss case need to install node-module and also jest testing famework (globally)
      - name: npm reinstall
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          npm install; npm install -g jest

      - name: testing
        run: |
          npm  test
