name: Test workflow

on:
  workflow_call:
jobs:
  test:
    name: test the application
    runs-on: ubuntu-latest
    steps:
      # Checkout the codebase
      - name: Checkout
        uses: actions/checkout@v4

      #OS Level dependencies
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      - name: Node Modules Cache
        id: node-cache
        uses: actions/cache@v4
        with:
          key: ${{ github.sha }}-node-nextjs-cache
          path: |
            ~/.npm
             node_modules

      # In cahce miss case need to install node-module and also jest testing famework (globally)
      - name: npm reinstall
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm install; npm install -g jest

      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build

      - name: testing
        run: npm run test
